# Use an official Python runtime as a parent image
FROM python:3.8-bullseye

# Set the working directory in the container
WORKDIR /app


# Install spaCy and English language model
RUN pip install mlflow


EXPOSE 8000

# Run the FastAPI application
CMD ["mlflow", "ui","--host" ,"0.0.0.0","--port", "8000"]
