version: '3.8'

services:
  mlflow:
    build:
      context: ./mlflow
    # networks:
    #     - model
    ports:
        - "8000:8000"
    

  mnist:
    build:
      context: ./mnist
    networks:
      - my_network
    volumes:
      - ./data:/app/data

# networks:
#   model:
#     driver: bridge
